config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  resources :messages, only: [:new, :create]

  namespace :admin do
    mount Ckeditor::Engine => '/ckeditor'

    root to: 'sessions#new'

    resources :abouts, only: [:new, :create, :edit, :update]
    resources :achievements, except: [:show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :services, except: [:show, :index]
    resources :portfolios, except: [:show]
    resources :posters, only: [:new, :create, :destroy]

    get '/dashboard' => 'dashboard#index'
    get 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new', as: 'login'
  end
end

app/models/about.rb
class About < ApplicationRecord
  validates_presence_of :body
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  mount_uploader :url, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :message
  belongs_to :service
end

app/models/diploma.rb
class Diploma < Achievement
end

app/models/letter.rb
class Letter < Achievement
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :full_name
  validates_presence_of :email
  validates_presence_of :phone

  phony_normalize :phone

  has_many :clients
  has_many :services, through: :clients
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :frame_code
  validates_presence_of :description
end

app/models/poster.rb
class Poster < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/service.rb
class Service < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :price
  validates_presence_of :description

  has_many :clients
  has_many :messages, through: :clients

  monetize :price_cents
end

app/controllers/admin/abouts_controller.rb
class Admin::AboutsController < AdminsController
  before_action :about_resource, only: [:edit, :update]

  def new
    @about = About.new
  end

  def create
    @about = About.create(about_params)
    if @about.save
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def update
    if @about.update(about_params)
      redirect_to admin_dashboard_path
    else
      render :edit
    end
  end

  private

  def about_params
    params.require(:about).permit(:body)
  end

  def about_resource
    @about = About.find(params[:id])
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminsController
  def index
    @services = Service.order(:id)
    @achievements = Achievement.order(:id)
    @porthfolios = Portfolio.order(:id).paginate(page: params[:page], per_page: 10)
    @messages = Message.order(:id)
    @about = About.first
    @posters = Poster.order(:id)
  end
end

app/controllers/admin/portfolios_controller.rb
class Admin::PortfoliosController < AdminsController
  before_action :project_resource, only: [:edit, :update, :destroy]

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.create(projects_params)
    if @portfolio.save
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def update
    if @portfolio.update(projects_params)
      redirect_to admin_dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @portfolio.destroy!
  end

  private

  def projects_params
    params.require(:portfolio).permit(:title, :description, :frame_code)
  end

  def project_resource
    @portfolio = Portfolio.find(params[:id])
  end
end

app/controllers/admin/posters_controller.rb
class Admin::PostersController < AdminsController
  before_action :poster_resource, only: [:destroy]

  def new
    @poster = Poster.new
  end

  def create
    @poster = Poster.create(image_params)
    if @poster.save
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def destroy
    @poster.destroy!
    redirect_back(fallback_location: admin_dashboard_path)
  end

  private

  def image_params
    params.require(:poster).permit(:image)
  end

  def poster_resource
    @poster = Poster.find(params[:id])
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminsController
  before_action :service_resource, only: [:edit, :update, :destroy]

  def new
    @service = Service.new
  end

  def create
    @service = Service.create(service_params)
    if @service.save
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def update
    if @service.update(service_params)
      redirect_to admin_dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @service.destroy!
    redirect_to admin_dashboard_path
  end

  private

  def service_params
    params.require(:service).permit(:name, :price, :description)
  end

  def service_resource
    @service = Service.find(params[:id])
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < AdminsController
  skip_before_action :require_admin, only: [:new, :create]

  def create
    if params[:email] == ENV['admin_email'] && params[:password] == ENV['admin_password']
      session[:admin] = true
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def destroy
    session[:admin] = false
    redirect_to admin_root_path
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout 'admin/application'

  before_action :require_admin

  private

  def require_admin
    redirect_to root_path unless session[:admin]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :meta_tags

  private

  def meta_tags
    $description = "Занимаемся услугами фото и видеосъёмок"
    $keywords = "NN VideoProd NNVideoProd Нижний Новгород
                 Дмитрий Романов дмитрий романов роман булычев
                 Роман Булычев NN Video Production"
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @about = About.first
    @achievements = Achievement.order(:type)
    @services = Service.order(:id)
    @porthfolios = Portfolio.order(:id).paginate(page: params[:page], per_page: 6)
    @message = Message.new
    @posters = Poster.order(:id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.create(message_resource)
    
    if @message.save
      MessageMailer.new_message(@message).deliver
      MessageMailer.message_deliver(@message).deliver
      redirect_to root_path, notice: 'Ваше сообщение успешно отправлено. С вами свяжуться в ближайшее время'
    else
      render :new
    end
  end

  private

  def message_resource
    params.require(:message).permit(:full_name, :email, :phone, :message, service_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/_achievements.html.slim
- @achievements.each do |achievement|
  .col.l4.s6
    = image_tag achievement.url.url(:medium), class: 'admin-image-portholio'
    p= link_to 'Удалить', admin_achievement_path(achievement), method: :delete, data: { confirm: 'Вы действительно хотите удалить эту картинку?' }

app/views/admin/dashboard/_messages.html.slim
.col.s12.m12.l12
  table.highlight
    thead
      tr
        th Имя
        th E-mail
        th Номер телефона
        th Список услуг
        th Комментарий
    tbody
      - @messages.each do |message|
        tr
          td= message.full_name
          td= message.email
          td= message.phone
          td
            - message.services.each do |service|
              li= service.name
          td= message.message

app/views/admin/dashboard/_portfolios.html.slim
- @porthfolios.each do |porth|
  .row
    .col.l2.s4.sm4
      .frame_place_list
        = raw porth.frame_code
        = link_to edit_admin_portfolio_path(porth) do
          i.material-icons edit
        = link_to admin_portfolio_path(porth), method: :delete, data: { confirm: 'Вы действительно хотите удалить эту работу?' } do
          i.material-icons delete
    .col.l6.s8.sm8
      b= porth.title
      p= truncate(porth.description, length: 200)

app/views/admin/dashboard/_posters.html.slim
- @posters.each do |poster|
    .col.l4.s6
      = image_tag poster.image_url(:medium), class: 'admin-image-portholio'
      p= link_to 'Удалить', admin_poster_path(poster), method: :delete, data: { confirm: 'Вы действительно хотите удалить эту картинку?' }

app/views/admin/dashboard/_services.html.slim
- @services.each_with_index do |service, i|
  tr
    td= i+1
    td= service.name
    td= service.description
    td= humanized_money_with_symbol service.price
    td
      = link_to edit_admin_service_path(service) do
        i.material-icons edit
      = link_to admin_service_path(service), method: :delete, data: { confirm: 'Вы действительно хотите удалить эту услугу?' } do
        i.material-icons delete

app/views/admin/dashboard/index.html.slim
h3 Услуги
.row
  .col.s12.m12.l8
    table.highlight
      thead
        tr
          th #
          th Название услуги
          th Описание
          th Цена
          th Действия
      tbody
        = render 'services'
.row
  = link_to 'Добавить услугу', new_admin_service_path, class: "black-text waves-effect waves-light btn lime accent-2"
h3 Портфолио
.row
  = render 'portfolios'
.row
  center
    = will_paginate @porthfolios, renderer: MaterializePagination::Rails
.row
  = link_to 'Добавить работу', new_admin_portfolio_path, class: "black-text waves-effect waves-light btn lime accent-3"
h3 Отличия
.row
  = render 'achievements'
.row
  = link_to 'Добавить награду', new_admin_achievement_path, class: "black-text waves-effect waves-light btn lime accent-3"
h3 Сообщения
.row
  = render 'messages'
h3 О нас
- if @about.present?
  = raw @about.body
  br
  = link_to 'Редактировать', edit_admin_about_path(@about)
- else
  = link_to 'Добавить информацио о нас', new_admin_about_path
h3 Фото-портфолио
.row.all_pictures
  = render 'posters'
.row
  = link_to 'Добавить картинку', new_admin_poster_path, class: "black-text waves-effect waves-light btn lime accent-3"

app/views/landing/_achievements.html.slim
.diplomas_desctop
  - @achievements.each do |achievement|
    .col.m4.sm12.l2.m3.diplomas
      a.carousel-item data-fancybox="diplomas" href="#{achievement.url.url(:big_large)}"
        = image_tag achievement.url.url(:medium), crop: "scale", class: 'diplom_image'
.diplomas_mobile
  - @achievements.each do |achievement|
    .col.m4.sm4.dip_mob
      a.carousel-item data-fancybox="diplomas_mobile" href="#{achievement.url.url(:big_large)}"
        = image_tag achievement.url.url(:medium), crop: "scale", class: 'diplom_image_mobile'

app/views/landing/_portfolios.html.slim
- @porthfolios.each do |porth|
  .col.s12.m6.l4
    .card.indigo.darken-4.2.project_cart
      br.line-port
      .white-text
        .title_video title="#{porth.title}"
          h5= truncate(porth.title, length: 40)
        .frame_place
          p= raw porth.frame_code
        .description title="#{porth.description}"
          p= truncate(porth.description, length: 80)
.row
  .col.s12
    center
      = will_paginate @porthfolios, renderer: MaterializePagination::Rails

app/views/landing/_posters.html.slim
- @posters.each do |poster|
  a.carousel-item data-fancybox="portholio" href="#{poster.image_url(:big_large)}"
    = image_tag poster.image_url(:medium), class: 'image-portholio'

app/views/landing/_price_list_modal.html.slim
#price_list_modal.modal
  .modal-header
    center
      h4 Полный список наших услуг
  .modal-content
    .col.m12.s12.sm12
      table.highlight
        thead
          tr
            th #
            th width='150px' Услуга
            th Описание
            th width='150px' Цена
        tbody
          - @services.each_with_index do |service, i|
            tr
              td= i+1
              td= service.name
              td= service.description
              td #{service.price} руб
  .modal-footer
    a.modal-action.modal-close.waves-effect.waves-green.btn.green Закрыть

app/views/landing/_services.html.slim
table.highlight.white
  thead
    tr
      th #
      th width='200px' Название услуги
      th Описание
      th width='150px' Цена
  tbody
    - @services.each_with_index do |service, i|
      tr
        td= i+1
        td= service.name
        td= service.description
        td #{service.price} руб

app/views/landing/index.html.slim
.row.about-us-block
  #AboutUs
    center= image_tag("menu/О_нас_cbtsgm.png", width: 500, crop: "scale", class: 'header-item')
  .col.s12.m12.l6
    .slider
      ul.slides
        li= image_tag 'backstages/1.jpg'
        li= image_tag 'backstages/2.jpg'
        li= image_tag 'backstages/3.jpg'
        li= image_tag 'backstages/4.png', class: 'image-carousel'
  .col.s12.m12.l6
    - if @about.present?
      = raw @about.body
.row
  #ServiceList
    center= image_tag("menu/Список_услуг_nvuiqd.png", width: 500, crop: "scale", class: 'header-item')
  .col.s12.m12.l8.offset-l2
    = render 'services'
.row
  center
    #Portholio
      center= image_tag("menu/Портфолио_qdvzlw.png", width: 500, crop: "scale", class: 'header-item')
    #port_list
      = render 'portfolios'
.row
  .carousel
    = render 'posters'
.row
  #Achievements
    center= image_tag("menu/Dostizhenia.png", height: 55, width: 450, crop: "scale", class: 'header-item')
  = render 'achievements'
.row
  #Contact
    center= image_tag("menu/Контакты_fvrb5b.png", width: 500, crop: "scale", class: 'header-item')
  .col.s12.m12.l5
    .col.s12.m6.l6
      p
      b Роман Булычев:
      p= fa_icon 'phone', text: '+7-908-159-50-44'
      p
      a href='https://vk.com/id248778866' target='_blank'
        = fa_icon 'vk', class: 'text-light-blue text-darken-4 fa-2x'
    .col.s12.m6.l6
      p
      b Дмитрий Романов:
      p= fa_icon 'phone', text: '+7-902-682-01-38'
      p
      a href='https://vk.com/project_rebel' target='_blank'
        = fa_icon 'vk', class: 'text-light-blue text-darken-4 fa-2x'
      p= fa_icon 'envelope', text: 'nnvideoprod@yandex.ru'
  .col.sm12.s12.l6
    .row
      = render 'messages/new'

app/views/landing/index.js.erb
$("#port_list").html("<%= escape_javascript(render("portfolios")) %>");
$('.pagination a').attr('data-remote', 'true');